name: Web Portfolio CI/CD
env:
  FLUTTER_VERSION: "2.0.6"

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE and downloads it to the runner
      - uses: actions/checkout@v2

      - name: Install ssh keys
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Rsync the build
        run: rsync -rv ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/html
